# Generated by Django 3.2.9 on 2021-12-31 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Postulante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('mail', models.CharField(max_length=40)),
                ('telefono', models.IntegerField(verbose_name='Teléfono')),
                ('presentacion', models.CharField(max_length=100, verbose_name='Presentación')),
                ('formacion', models.CharField(max_length=100, verbose_name='Formación')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Postulante', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
