# Generated by Django 3.2.9 on 2021-12-14 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Postulante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('mail', models.CharField(max_length=40)),
                ('telefono', models.IntegerField(max_length=10)),
                ('presentacion', models.CharField(max_length=100)),
                ('formacion', models.CharField(max_length=100)),
            ],
        ),
    ]
