# Generated by Django 3.2.9 on 2022-01-02 22:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Requeridos', '0002_alter_requeridos_fechapublicacion'),
        ('Postulantes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulante',
            name='requerido',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Requeridos.requeridos'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postulante',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postulante', to=settings.AUTH_USER_MODEL),
        ),
    ]
