# Generated by Django 3.2.9 on 2022-01-08 22:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Perfiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Postulantes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postulante',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='postulante',
            name='mail',
        ),
        migrations.RemoveField(
            model_name='postulante',
            name='nombre',
        ),
        migrations.AddField(
            model_name='postulante',
            name='avatarP',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Perfiles.avatar'),
        ),
        migrations.AlterField(
            model_name='postulante',
            name='formacion',
            field=models.CharField(max_length=300, verbose_name='Formación'),
        ),
        migrations.AlterField(
            model_name='postulante',
            name='presentacion',
            field=models.CharField(max_length=300, verbose_name='Presentación'),
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField(max_length=300)),
                ('usuPostulado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Postulantes.postulante')),
                ('usuarioM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
