# Generated by Django 3.2.9 on 2022-01-09 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Postulantes', '0002_auto_20220108_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postulante',
            name='avatarP',
        ),
    ]
