# Generated by Django 3.2.9 on 2022-01-09 04:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Postulantes', '0003_remove_postulante_avatarp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensaje',
            old_name='usuarioM',
            new_name='de',
        ),
        migrations.RenameField(
            model_name='mensaje',
            old_name='usuPostulado',
            new_name='post',
        ),
        migrations.AddField(
            model_name='mensaje',
            name='para',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='para', to='auth.user'),
            preserve_default=False,
        ),
    ]
