# Generated by Django 3.2.9 on 2021-12-15 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Postulantes', '0003_requeridos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requeridos',
            old_name='situacion',
            new_name='interno',
        ),
    ]
