# Generated by Django 3.2.9 on 2021-12-16 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Postulantes', '0003_requeridos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requeridos',
            name='deLaEmpresa',
            field=models.BooleanField(null=True),
        ),
    ]
