# Generated by Django 3.2.9 on 2022-01-04 04:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Requeridos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicion', models.CharField(max_length=40, verbose_name='Posición')),
                ('sector', models.CharField(max_length=40)),
                ('descripcion', models.CharField(max_length=400, verbose_name='Descripción')),
                ('formacionReq', models.CharField(max_length=40, verbose_name='Formación requerida')),
                ('deLaEmpresa', models.BooleanField(null=True, verbose_name='Interno de la empresa')),
                ('propMonetaria', models.IntegerField(verbose_name='Propuesta monetaria')),
                ('fechaPublicacion', models.DateField(default=datetime.date(2022, 1, 4), verbose_name='Fecha de publicación')),
            ],
        ),
    ]
